plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  "@apollographql/apollo-tools@*":
    dependencies:
      "graphql": "^14.0.2"
  
  "apollo-datasource-rest@0.9.2":
    dependencies:
      "graphql": "^14.0.2"
      "apollo-server-types": "*"

  "apollo-engine-reporting-protobuf@*":
    dependencies:
      "long": "*"

  "apollo-server-errors@*":
    peerDependencies:
      "graphql": "^14.0.2"

  "apollo-upload-client@13.0.0":
    dependencies:
      "graphql": "^14.0.2"

  "postgraphile@4.7.0":
    dependencies:
      "graphql": "^14.0.2"
      "graphile-build": "^4.7.0"
      "graphile-build-pg": "^4.7.0"

  "graphile-build-pg@4.7.0":
    dependencies:
      "graphql": "^14.0.2"

  "graphile-utils@4.7.0":
    dependencies:
      "tslib": "*"
